"""Initial schema

Revision ID: 50eb71ecb990
Revises: 
Create Date: 2026-08-14 20:51:27.278939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50eb71ecb990'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=True),
    sa.Column('inviter_type', sa.String(length=16), nullable=False),
    sa.Column('invitee_email', sa.String(length=200), nullable=False),
    sa.Column('invitee_type', sa.String(length=16), nullable=False),
    sa.Column('referral_code', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('accepted_id', sa.Integer(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('theme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('css_url', sa.String(length=150), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=200), nullable=True),
    sa.Column('starter_html', sa.Text(), nullable=True),
    sa.Column('contact_html', sa.Text(), nullable=True),
    sa.Column('homepage_css', sa.Text(), nullable=True),
    sa.Column('contact_css', sa.Text(), nullable=True),
    sa.Column('products_html', sa.Text(), nullable=True),
    sa.Column('products_css', sa.Text(), nullable=True),
    sa.Column('homepage_js', sa.Text(), nullable=True),
    sa.Column('contact_js', sa.Text(), nullable=True),
    sa.Column('products_js', sa.Text(), nullable=True),
    sa.Column('preview_home', sa.Text(), nullable=True),
    sa.Column('preview_home_css', sa.Text(), nullable=True),
    sa.Column('preview_home_js', sa.Text(), nullable=True),
    sa.Column('preview_products', sa.Text(), nullable=True),
    sa.Column('preview_products_css', sa.Text(), nullable=True),
    sa.Column('preview_products_js', sa.Text(), nullable=True),
    sa.Column('preview_contact', sa.Text(), nullable=True),
    sa.Column('preview_contact_css', sa.Text(), nullable=True),
    sa.Column('preview_contact_js', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_account_id', sa.String(length=128), nullable=True),
    sa.Column('earnings_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('grand_total_earnings', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('withdrawn_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('referral_code', sa.String(length=32), nullable=True),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.Column('business_referral_id', sa.String(length=32), nullable=True),
    sa.Column('email_confirmed', sa.Boolean(), nullable=True),
    sa.Column('email_code', sa.String(length=16), nullable=True),
    sa.Column('profile_photo', sa.String(length=200), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), nullable=True),
    sa.Column('investor_share', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('investor_total_earnings', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('investor_withdrawn_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('investor_earnings_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['sponsor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('referral_code')
    )
    op.create_table('business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=100), nullable=False),
    sa.Column('store_slug', sa.String(length=80), nullable=True),
    sa.Column('theme_id', sa.Integer(), nullable=True),
    sa.Column('custom_html', sa.Text(), nullable=True),
    sa.Column('grapesjs_html', sa.Text(), nullable=True),
    sa.Column('grapesjs_css', sa.Text(), nullable=True),
    sa.Column('stripe_account_id', sa.String(length=100), nullable=True),
    sa.Column('earnings_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('grand_total_earnings', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('withdrawn_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('has_ecommerce_store', sa.Boolean(), nullable=True),
    sa.Column('listing_type', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('finalization', sa.String(length=50), nullable=True),
    sa.Column('perks', sa.Text(), nullable=True),
    sa.Column('business_email', sa.String(length=200), nullable=False),
    sa.Column('website_approved', sa.Boolean(), nullable=True),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('referral_code', sa.String(length=32), nullable=True),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.Column('user_sponsor_id', sa.Integer(), nullable=True),
    sa.Column('email_confirmed', sa.Boolean(), nullable=True),
    sa.Column('email_code', sa.String(length=16), nullable=True),
    sa.Column('profile_photo', sa.String(length=200), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('hours_of_operation', sa.String(length=100), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('about_us', sa.Text(), nullable=True),
    sa.Column('service_1', sa.String(length=100), nullable=True),
    sa.Column('service_2', sa.String(length=100), nullable=True),
    sa.Column('service_3', sa.String(length=100), nullable=True),
    sa.Column('service_4', sa.String(length=100), nullable=True),
    sa.Column('service_5', sa.String(length=100), nullable=True),
    sa.Column('service_6', sa.String(length=100), nullable=True),
    sa.Column('service_7', sa.String(length=100), nullable=True),
    sa.Column('service_8', sa.String(length=100), nullable=True),
    sa.Column('service_9', sa.String(length=100), nullable=True),
    sa.Column('service_10', sa.String(length=100), nullable=True),
    sa.Column('search_keywords', sa.String(length=500), nullable=True),
    sa.Column('draft_business_name', sa.String(length=100), nullable=True),
    sa.Column('draft_listing_type', sa.String(length=50), nullable=True),
    sa.Column('draft_category', sa.String(length=50), nullable=True),
    sa.Column('draft_finalization', sa.String(length=50), nullable=True),
    sa.Column('draft_profile_photo', sa.String(length=200), nullable=True),
    sa.Column('draft_phone_number', sa.String(length=30), nullable=True),
    sa.Column('draft_address', sa.String(length=255), nullable=True),
    sa.Column('draft_latitude', sa.Float(), nullable=True),
    sa.Column('draft_longitude', sa.Float(), nullable=True),
    sa.Column('draft_hours_of_operation', sa.String(length=100), nullable=True),
    sa.Column('draft_website_url', sa.String(length=255), nullable=True),
    sa.Column('draft_about_us', sa.Text(), nullable=True),
    sa.Column('draft_service_1', sa.String(length=100), nullable=True),
    sa.Column('draft_service_2', sa.String(length=100), nullable=True),
    sa.Column('draft_service_3', sa.String(length=100), nullable=True),
    sa.Column('draft_service_4', sa.String(length=100), nullable=True),
    sa.Column('draft_service_5', sa.String(length=100), nullable=True),
    sa.Column('draft_service_6', sa.String(length=100), nullable=True),
    sa.Column('draft_service_7', sa.String(length=100), nullable=True),
    sa.Column('draft_service_8', sa.String(length=100), nullable=True),
    sa.Column('draft_service_9', sa.String(length=100), nullable=True),
    sa.Column('draft_service_10', sa.String(length=100), nullable=True),
    sa.Column('draft_search_keywords', sa.String(length=500), nullable=True),
    sa.Column('account_balance', sa.Float(), nullable=False),
    sa.Column('ad_fee', sa.Float(), nullable=True),
    sa.Column('business_registration_doc', sa.String(length=255), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.Column('rank', sa.Float(), nullable=True),
    sa.Column('manual_feature', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('homepage_html', sa.Text(), nullable=True),
    sa.Column('contact_html', sa.Text(), nullable=True),
    sa.Column('contact_css', sa.Text(), nullable=True),
    sa.Column('products_html', sa.Text(), nullable=True),
    sa.Column('products_css', sa.Text(), nullable=True),
    sa.Column('grapesjs_js', sa.Text(), nullable=True),
    sa.Column('products_js', sa.Text(), nullable=True),
    sa.Column('contact_js', sa.Text(), nullable=True),
    sa.Column('theme_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sponsor_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['theme.id'], ),
    sa.ForeignKeyConstraint(['user_sponsor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_email'),
    sa.UniqueConstraint('business_name'),
    sa.UniqueConstraint('referral_code'),
    sa.UniqueConstraint('store_slug')
    )
    op.create_table('conversation_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investor_earnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'business_id', name='_user_business_uc')
    )
    op.create_table('interaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('budget_low', sa.Float(), nullable=True),
    sa.Column('budget_high', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('referral_code', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('awaiting_finalization', sa.Boolean(), nullable=True),
    sa.Column('awaiting_payment', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=200), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('password_reset_required', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'email', name='uniq_staff_per_biz'),
    sa.UniqueConstraint('email')
    )
    op.create_table('business_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=48), nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('local_date_time', sa.String(length=32), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('business_referral_id', sa.String(length=32), nullable=False),
    sa.Column('cash_back', sa.Float(), nullable=False),
    sa.Column('tier2_business_referral_id', sa.String(length=32), nullable=False),
    sa.Column('tier2_commission', sa.Float(), nullable=False),
    sa.Column('tier3_business_referral_id', sa.String(length=32), nullable=False),
    sa.Column('tier3_commission', sa.Float(), nullable=False),
    sa.Column('tier4_business_referral_id', sa.String(length=32), nullable=False),
    sa.Column('tier4_commission', sa.Float(), nullable=False),
    sa.Column('tier5_business_referral_id', sa.String(length=32), nullable=False),
    sa.Column('tier5_commission', sa.Float(), nullable=False),
    sa.Column('ad_fee', sa.Float(), nullable=True),
    sa.Column('sponsoree_mutual_referral_id', sa.String(length=32), nullable=True),
    sa.Column('sponsoree_mutual_commission', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['interaction_id'], ['interaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_transaction_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('finalized_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tx_id', sa.String(length=48), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finalized_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finalized_transaction_tx_id'), ['tx_id'], unique=False)

    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.String(length=16), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('file_url', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['interaction_id'], ['interaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('buyer_email', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('stripe_checkout_id', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('fulfillment_token', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interaction_id'], ['interaction.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interaction_id')
    )
    op.create_table('user_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=48), nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('local_date_time', sa.String(length=32), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('user_referral_id', sa.String(length=32), nullable=False),
    sa.Column('cash_back', sa.Float(), nullable=False),
    sa.Column('tier2_user_referral_id', sa.String(length=32), nullable=False),
    sa.Column('tier2_commission', sa.Float(), nullable=False),
    sa.Column('tier3_user_referral_id', sa.String(length=32), nullable=False),
    sa.Column('tier3_commission', sa.Float(), nullable=False),
    sa.Column('tier4_user_referral_id', sa.String(length=32), nullable=False),
    sa.Column('tier4_commission', sa.Float(), nullable=False),
    sa.Column('tier5_user_referral_id', sa.String(length=32), nullable=False),
    sa.Column('tier5_commission', sa.Float(), nullable=False),
    sa.Column('business_referral_id', sa.String(length=32), nullable=True),
    sa.Column('tier1_business_user_referral_id', sa.String(length=32), nullable=True),
    sa.Column('tier1_business_user_commission', sa.Float(), nullable=True),
    sa.Column('tier2_business_user_referral_id', sa.String(length=32), nullable=True),
    sa.Column('tier2_business_user_commission', sa.Float(), nullable=True),
    sa.Column('tier3_business_user_referral_id', sa.String(length=32), nullable=True),
    sa.Column('tier3_business_user_commission', sa.Float(), nullable=True),
    sa.Column('tier4_business_user_referral_id', sa.String(length=32), nullable=True),
    sa.Column('tier4_business_user_commission', sa.Float(), nullable=True),
    sa.Column('tier5_business_user_referral_id', sa.String(length=32), nullable=True),
    sa.Column('tier5_business_user_commission', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['interaction_id'], ['interaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_transaction_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_transaction_transaction_id'))

    op.drop_table('user_transaction')
    op.drop_table('quote')
    op.drop_table('order')
    op.drop_table('message')
    with op.batch_alter_table('finalized_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finalized_transaction_tx_id'))

    op.drop_table('finalized_transaction')
    with op.batch_alter_table('business_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_transaction_transaction_id'))

    op.drop_table('business_transaction')
    op.drop_table('staff')
    op.drop_table('product')
    op.drop_table('interaction')
    op.drop_table('favorite')
    op.drop_table('user_roles')
    op.drop_table('investor_earnings')
    op.drop_table('conversation_participant')
    op.drop_table('business')
    op.drop_table('user')
    op.drop_table('theme')
    op.drop_table('role')
    op.drop_table('invite')
    op.drop_table('conversation')
    # ### end Alembic commands ###
